apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: shop-online
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017

        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: shop-online-config
                key: MONGO_INITDB_ROOT_USERNAME
                
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: shop-online-config
                key: MONGO_INITDB_ROOT_PASSWORD

          - name: MONGO_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: shop-online-config
                key: MONGO_DB_HOST

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

      #   volumeMounts:
      #   - name:  mongo-pvc
      #     mountPath: /data/db # default path should be /data/db its for mongodb
      # volumes:
      #   - name: mongo-pvc
      #     persistentVolumeClaim:
      #       claimName: mongo-pvc    

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: shop-online
spec:
  selector:
    app: ClusterIp
  nodePort: 30007
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017