apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-online-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shlomo-b/Shop-Online.git
    path: ./apps/shop-online
  destination:
    server: https://kubernetes.default.svc
    namespace: shop-online
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true